# run with:
# mkdir .git/hooks
# hookz initialize --verbose-output
# hookz reset --verbose-output
#
hooks:
  - type: pre-commit
    actions:
      - name: "run pre-commit-checks"
        exec: "bash"
        args: ["./run", "tests"]
  - type: pre-rebase
    actions:
      - name: "run pre-commit-checks"
        exec: "bash"
        args: ["./run", "tests"]
