# run with:
# mkdir .git/hooks
# hookz initialize --verbose-output
# hookz reset --verbose-output
#
hooks:
  - type: pre-commit
    actions:
      - name: "make pre-commit-checks"
        exec: "make"
        args: ["tests"]
  - type: pre-rebase
    actions:
      - name: "make pre-commit-checks"
        exec: "make"
        args: ["tests"]
