# PROD
ACCESS_KEY = "ACCESSKEY"
SECRET_KEY = "SECRETKEY"
MODE = "analyse"

PAUSE_FOR = 30
INITIAL_INVESTMENT = 100
HOLDING_TIME = 30 # 30 * 240 = 7200s
MAX_COINS = 1
PAIRING="USDT"


BUY_AT_PERCENTAGE = -2
SELL_AT_PERCENTAGE = +1.0
STOP_LOSS_AT_PERCENTAGE = -10
CLEAR_COIN_STATS_AT_BOOT = False
TRAIL_TARGET_SELL_PERCENTAGE = -0.3  # when profit goes down the tip by %, sell
TRAIL_RECOVERY_PERCENTAGE = +1.0 # when recovery goes over the dip by %, buy
NAUGHTY_TIMEOUT = 4
CLEAR_COIN_STATS_AT_SALE = True
DEBUG = False

TICKERS = [line.strip() for line in open("tickers.txt")]
TRADING_FEE = "0.01"

PRICE_LOGS = ["log/20210922.log.gz"]

EXCLUDED_COINS = [
    'DOWNUSDT',
    'UPUSDT',
]

# FOR TESTING using TESTNET:
#------------------------------------
# https://testnet.binance.vision/
#MODE = "testnet"  # NOTE: use testnet or analyse
#ACCESS_KEY = "TESTNETACCESSKEY"
#SECRET_KEY = "TESTNETSECRETKEY"
#INITIAL_INVESTMENT = 10000
#PAUSE_FOR = 10
#BUY_AT_PERCENTAGE = 99.999
#SELL_AT_PERCENTAGE = 100.00001
#STOP_LOSS_AT_PERCENTAGE = 99.99999
#EXCLUDED_COINS = [
#  'DOWNUSDT',
#  'UPUSDT',
#]
#PRICE_LOG = "testnet.log"

