version: '3'
services:
  cryptobot:
    networks:
      - cryptobot-network
    image: ${IMAGE:-ghcr.io/azulinho/cryptobot}:${TAG:-latest}
    user: "${U}:${G}"
    build: ./
    privileged: false
    environment:
      SMP_MULTIPLIER: "${SMP_MULTIPLIER:-1}"
    depends_on:
      - klines

    ports:
      - "5555"

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./configs:/cryptobot/configs
      - ./secrets:/cryptobot/secrets:ro
      - ./log:/cryptobot/log:rw
      - ./state:/cryptobot/state:rw
      - ./cache:/cryptobot/cache:rw
      - ./results:/cryptobot/results:rw
      - ./tests:/cryptobot/tests:rw

  klines:
    networks:
      - cryptobot-network
    image: ${IMAGE:-ghcr.io/azulinho/cryptobot}:${TAG:-latest}
    user: "${U}:${G}"
    build: ./
    entrypoint: ["/cryptobot/.venv/bin/python", "-u",  "load_klines_for_coin.py"]
    privileged: false

    ports:
      - "8999"

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./log:/cryptobot/log:rw
      - ./cache:/cryptobot/cache:rw


networks:
  cryptobot-network:
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "${IP:-172.20.0.1}"
    ipam:
      config:
        - subnet: "${NET:-172.20.0.0/16}"
