version: '3'
services:

  cryptobot:
    container_name: cryptobot-${DCOMPOSE_ID}-${WHOAMI}
    image: ${IMAGE:-ghcr.io/azulinho/cryptobot}:${TAG:-latest}
    user: "${U}:${G}"
    build: ./
    privileged: false
    entrypoint: ["/cryptobot/.venv/bin/python", "-u",  "app.py"]
    depends_on:
      - klines
    profiles:
      - backtesting
      - download-price-logs
      - live
      - logmode
      - testnet
    ports:
      - ${BIND}:${PORT1}:5555
    volumes: &FULL_VOL_LIST
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./configs:/cryptobot/configs
      - ./secrets:/cryptobot/secrets:ro
      - ./log:/cryptobot/log:rw
      - ./state:/cryptobot/state:rw
      - ./cache:/cryptobot/cache:rw
      - ./results:/cryptobot/results:rw
      - ./tests:/cryptobot/tests:rw
      - ./control:/cryptobot/control:rw

  klines:
    container_name: klines-${DCOMPOSE_ID}-${WHOAMI}
    image: ${IMAGE:-ghcr.io/azulinho/klines_caching_service}:${TAG:-latest}
    user: "${U}:${G}"
    build: ./klines_caching_service/
    privileged: false
    ports:
      - ${BIND}:${PORT3}:8999
    profiles:
      - automated-backtesting
      - backtesting
      - build
      - config-endpoint-service
      - live
      - prove-backtesting
      - testnet
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./log:/cryptobot/log:rw
      - ./cache:/cryptobot/cache:rw

  automated-backtesting:
    container_name: automated-backtesting-${DCOMPOSE_ID}-${WHOAMI}
    image: ${IMAGE:-ghcr.io/azulinho/cryptobot}:${TAG:-latest}
    user: "${U}:${G}"
    build: ./
    privileged: false
    entrypoint: ["/cryptobot/utils/automated-backtesting.sh"]
    environment:
      SMP_MULTIPLIER: "${SMP_MULTIPLIER:-1}"
    depends_on:
      - klines
    profiles:
      - automated-backtesting
    volumes: *FULL_VOL_LIST

  config-endpoint-service:
    container_name: config-endpoint-service-${DCOMPOSE_ID}-${WHOAMI}
    image: ${IMAGE:-ghcr.io/azulinho/cryptobot}:${TAG:-latest}
    user: "${U}:${G}"
    build: ./
    privileged: false
    ports:
      - ${BIND}:${PORT2}:5883
    environment:
      SMP_MULTIPLIER: "${SMP_MULTIPLIER:-1}"
    depends_on:
      - klines
    profiles:
      - config-endpoint-service
    volumes: *FULL_VOL_LIST
    entrypoint: ["/cryptobot/utils/config-endpoint-service.sh"]

  prove-backtesting:
    container_name: prove-backtesting-${DCOMPOSE_ID}-${WHOAMI}
    image: ${IMAGE:-ghcr.io/azulinho/cryptobot}:${TAG:-latest}
    user: "${U}:${G}"
    build: ./
    privileged: false
    environment:
      SMP_MULTIPLIER: "${SMP_MULTIPLIER:-1}"
    depends_on:
      - klines
    profiles:
      - prove-backtesting
    entrypoint: ["/cryptobot/utils/prove-backtesting.sh"]
    volumes: *FULL_VOL_LIST

  download-price-logs:
    container_name: download-price-logs-${DCOMPOSE_ID}-${WHOAMI}
    image: ${IMAGE:-ghcr.io/azulinho/cryptobot}:${TAG:-latest}
    user: "${U}:${G}"
    build: ./
    privileged: false
    entrypoint: ["/cryptobot/.venv/bin/python", "-u",  "/cryptobot/utils/pull_klines.py"]
    profiles:
      - download-price-logs
    volumes: *FULL_VOL_LIST
