version: '3'
services:
  cryptobot:
    image: ${IMAGE:-ghcr.io/azulinho/cryptobot}:${TAG:-latest}
    user: "${U}:${G}"
    build: ./
    privileged: false
    environment:
      SMP_MULTIPLIER: "${SMP_MULTIPLIER:-1}"
    depends_on:
      - klines

    ports:
      - "127.0.0.1:${PORT1}:5555"

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./configs:/cryptobot/configs
      - ./secrets:/cryptobot/secrets:ro
      - ./log:/cryptobot/log:rw
      - ./state:/cryptobot/state:rw
      - ./cache:/cryptobot/cache:rw
      - ./results:/cryptobot/results:rw
      - ./tests:/cryptobot/tests:rw
      - ./control:/cryptobot/control:rw

  klines:
    image: ${IMAGE:-ghcr.io/azulinho/cryptobot}:${TAG:-latest}
    user: "${U}:${G}"
    build: ./
    entrypoint: ["/cryptobot/.venv/bin/python", "-u",  "klines_caching_service.py"]
    privileged: false

    ports:
      - "127.0.0.1:${PORT2}:8999"

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./log:/cryptobot/log:rw
      - ./cache:/cryptobot/cache:rw
