version: '3'
services:
  cryptobot:
    image: ghcr.io/azulinho/cryptobot
    user: "${U}:${G}"
    build: ./

    ports:
      - "5555"

    volumes:
      - ./configs:/configs
      - ./secrets:/secrets
      - ./log:/cryptobot/log:rw
      - ./state:/cryptobot/state:rw
      - ./cache:/cryptobot/cache:rw
