version: '3'
services:
  cryptobot:
    image: ghcr.io/azulinho/cryptobot
    user: "${U}:${G}"
    build: ./

    ports:
      - "5555"

    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./configs:/cryptobot/configs
      - ./secrets:/cryptobot/secrets:ro
      - ./log:/cryptobot/log:rw
      - ./state:/cryptobot/state:rw
      - ./cache:/cryptobot/cache:rw
      - ./results:/cryptobot/results:rw
      - ./tests:/cryptobot/tests:rw
