# FOR TESTING using TESTNET:
#------------------------------------
# https://testnet.binance.vision/
MODE = "testnet"
ACCESS_KEY = "TESTNET ACCESS_KEY"
SECRET_KEY = "TESTNET SECRET_KEY"
INITIAL_INVESTMENT = 100
PAIRING="USDT"
PAUSE_FOR = 1
BUY_AT_PERCENTAGE = -0.001
SELL_AT_PERCENTAGE = +0.001
STOP_LOSS_AT_PERCENTAGE = -0.3
TRAIL_TARGET_SELL_PERCENTAGE = -0.001
TRAIL_RECOVERY_PERCENTAGE = +0.001
SOFT_LIMIT_HOLDING_TIME = 7200
HARD_LIMIT_HOLDING_TIME = 604800
CLEAR_COIN_STATS_AT_BOOT = True
NAUGHTY_TIMEOUT = 28800
CLEAR_COIN_STATS_AT_SALE = True
DEBUG = False
MAX_COINS = 3
TICKERS_FILE = "tickers/all.txt"
#STRATEGY="buy_moon_sell_recovery_strategy"
STRATEGY="buy_drop_sell_recovery_strategy"
TRADING_FEE = 0.01
PRICE_LOGS = [""]

EXCLUDED_COINS = [
    'DOWNUSDT',
    'UPUSDT',
]
