# Generated by Django 5.0.1 on 2024-01-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mappings",
            fields=[
                (
                    "filename",
                    models.CharField(
                        max_length=256, primary_key=True, serialize=False
                    ),
                ),
                ("timeframe", models.CharField(max_length=3)),
                ("symbol", models.CharField(max_length=32)),
                ("pair", models.CharField(max_length=32)),
                ("open_timestamp", models.BigIntegerField()),
                ("close_timestamp", models.BigIntegerField()),
            ],
        ),
    ]
