name: Build and publish Docker images on a git tag push
on:
  push:
    tags:
      - "*"
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Docker meta klines_caching_service image
        id: meta_klines_caching_service_img
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/azulinho/klines_caching_service
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=sha
            type=raw,value=latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta_klines_caching_service_img.outputs.tags }}
          labels: ${{ steps.meta_klines_caching_service_img.outputs.labels }}
          push: true
          context: ./klines_caching_service
          no-cache: true
