name: Run build on next_release
on:
  push:
    branches:
      - "next_release"

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull latest upstream base
        run: |
          docker pull bitnami/minideb:bullseye
          docker pull ghcr.io/azulinho/cryptobot:latest

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/azulinho/cryptobot:next_release
          push: true

