name: Run PR tests
on: pull_request

jobs:
  tests:
    name: Run PR tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v1

      - name: pip install
        run: |
          set -e
          pip install wheel
          pip install -r requirements.txt
          pip installs requirements-dev.txt

      - name: pylint
        run: pylint app.pyt

      - name: pytest
        run: pytest tests/

      - name: local docker-compose build
        run: |
          set -e
          pip install docker-compose
          docker-compose build
