name: Run lint and syntax tests on a Pull Request
on: pull_request

jobs:
  pr_tests:
    name: Run PR tests
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: retrieve cached ta-lib
        id: cache-ta-lib
        uses: actions/cache@v3
        with:
          path: /tmp/ta-lib
          key: ta-lib

      - name: retrieve cached pip packages
        id: cache-pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-dev.txt') }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('.python-version') }}

      - name: install apt-packages
        run: |
          sudo apt-get update
          sudo  DEBIAN_FRONTEND=noninteractive apt-get install -yq eatmydata
          sudo  DEBIAN_FRONTEND=noninteractive eatmydata apt-get install -yq \
          make \
          build-essential \
          libssl-dev \
          zlib1g-dev \
          libbz2-dev \
          libisal-dev \
          libisal2 \
          libreadline-dev \
          libsqlite3-dev \
          wget \
          curl \
          llvm \
          libncursesw5-dev \
          xz-utils \
          tk-dev \
          libxml2-dev \
          libxmlsec1-dev \
          libffi-dev \
          liblzma-dev \
          git \
          ca-certificates \
          cargo \
          gzip \
          pigz \
          bzip2 \
          pbzip2 \
          autoconf \
          automake \
          shtool \
          coreutils \
          autogen \
          libtool \
          shtool \
          nasm

      - name: install ta-lib
        run: |
          cd /tmp \
          && eatmydata wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz \
          && eatmydata tar xf ta-lib-0.4.0-src.tar.gz \
          && cd ta-lib \
          && eatmydata ./configure --prefix=/usr \
          && eatmydata make \
          && sudo eatmydata make install

      - name: run setup
        run: eatmydata ./run setup

      - name: run cryptobot tests
        run: eatmydata ./run tests
