name: Run lint and syntax tests on a Pull Request
on: pull_request

jobs:
  pr_tests:
    name: Run PR tests
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: install build-essentials
        run: sudo apt-get -y install build-essential

      - name: install ta-lib
        run: |
          cd /tmp \
          && wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz \
          && tar xf ta-lib-0.4.0-src.tar.gz \
          && cd ta-lib \
          && ./configure --prefix=/usr \
          && make \
          && sudo make install

      - name: run setup
        run: ./run setup

      - name: run cryptobot tests
        run: ./run tests
